# Biome Type Sources:
# http://mynasadata.larc.nasa.gov/glossary/all-biome-types/
# http://minecraft.gamepedia.com/Biome

biomes = [
"evergreen needleleaf forest",
"evergreen broadleaf forest",
"deciduous needleleaf forest",
"deciduous broadleaf forest",
"shrubland",
"woody savanna",
"desert",
"savanna",
"grassland",
"wetland",
"cropland",
"city",
"tundra",
"ocean",
"plains",
"sunflower plains",
"desert",
"extreme hills",
"forest",
"taiga",
"swampland",
"river",
"hell",
"end",
"frozen ocean",
"frozen river",
"sunflower ice plains",
"ice mountains",
"mushroom island",
"mushroom island shore",
"desert hills",
"forest hills",
"taiga hills",
"extreme hills edge",
"jungle",
"jungle hills",
"jungle edge",
"deep ocean",
"birch forest",
"birch forest hills",
"roofed forest",
"cold taiga",
"cold taiga hills",
"mega taiga",
"mega taiga hills",
"extreme hills",
"savanna",
"savanna plateau",
"mesa",
"mesa plateau forest",
"mesa plateau",
"void",
]
